# Generated by Django 6.0.7 on 2026-08-06 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tip_minor',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('initial_amount_minor', models.PositiveBigIntegerField()),
                ('balance_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_gift_cards', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='commerce.giftcard')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.order')),
            ],
        ),
    ]
