# Generated by Django 6.0.7 on 2026-08-07 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_tip_minor_giftcard_giftcardtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('refunded', 'Refunded')], default='requested', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('refund_amount_minor', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='commerce.order')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('seller_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='commerce.sellerorder')),
            ],
        ),
    ]
