# Generated by Django 6.0.7 on 2026-08-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_checkoutattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_token',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
