from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("shops", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Attribute", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100)), ("slug", models.SlugField(max_length=120, unique=True)), ("input_type", models.CharField(default="text", max_length=20))]),
        migrations.CreateModel(name="Category", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("slug", models.SlugField(max_length=160)), ("description", models.TextField(blank=True)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="catalog.category")), ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="shops.shop"))], options={"ordering": ("name",)}),
        migrations.CreateModel(name="Collection", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("slug", models.SlugField(max_length=160)), ("description", models.TextField(blank=True)), ("is_active", models.BooleanField(default=True)), ("starts_at", models.DateTimeField(blank=True, null=True)), ("ends_at", models.DateTimeField(blank=True, null=True)), ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="collections", to="shops.shop"))]),
        migrations.CreateModel(name="Product", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=250)), ("slug", models.SlugField(max_length=270)), ("description", models.TextField(blank=True)), ("product_type", models.CharField(default="physical", max_length=50)), ("brand", models.CharField(blank=True, max_length=120)), ("status", models.CharField(choices=[("draft", "Draft"), ("pending", "Pending review"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)), ("is_digital", models.BooleanField(default=False)), ("requires_shipping", models.BooleanField(default=True)), ("seo_title", models.CharField(blank=True, max_length=250)), ("seo_description", models.CharField(blank=True, max_length=320)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="products", to="catalog.category")), ("collections", models.ManyToManyField(blank=True, related_name="products", to="catalog.collection")), ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_products", to=settings.AUTH_USER_MODEL)), ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to="shops.shop"))], options={"indexes": [models.Index(fields=["shop", "status"], name="catalog_pro_shop_id_1ab9c4_idx"), models.Index(fields=["name"], name="catalog_pro_name_34c45a_idx")]}),
        migrations.CreateModel(name="ProductAttributeValue", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("value", models.CharField(max_length=500)), ("attribute", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_values", to="catalog.attribute")), ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attribute_values", to="catalog.product"))]),
        migrations.CreateModel(name="ProductVariant", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(blank=True, max_length=250)), ("sku", models.CharField(max_length=100)), ("barcode", models.CharField(blank=True, max_length=100)), ("option_values", models.JSONField(blank=True, default=dict)), ("price_minor", models.PositiveBigIntegerField()), ("compare_at_price_minor", models.PositiveBigIntegerField(blank=True, null=True)), ("currency", models.CharField(default="NGN", max_length=3)), ("weight_grams", models.PositiveIntegerField(default=0)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="catalog.product"))], options={"indexes": [models.Index(fields=["sku"], name="catalog_pro_sku_3c2d65_idx"), models.Index(fields=["product", "is_active"], name="catalog_pro_product_70bd5c_idx")]}),
        migrations.CreateModel(name="BundleComponent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quantity", models.PositiveIntegerField(default=1)), ("bundle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bundle_components", to="catalog.productvariant")), ("component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="used_in_bundles", to="catalog.productvariant"))]),
        migrations.CreateModel(name="Warehouse", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("code", models.SlugField(max_length=80)), ("address", models.JSONField(blank=True, default=dict)), ("is_active", models.BooleanField(default=True)), ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="warehouses", to="shops.shop"))]),
        migrations.CreateModel(name="StockItem", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("on_hand", models.IntegerField(default=0)), ("reserved", models.IntegerField(default=0)), ("reorder_level", models.PositiveIntegerField(default=0)), ("updated_at", models.DateTimeField(auto_now=True)), ("variant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_items", to="catalog.productvariant")), ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_items", to="catalog.warehouse"))]),
        migrations.CreateModel(name="InventoryLedgerEntry", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quantity_delta", models.IntegerField()), ("reason", models.CharField(max_length=40)), ("reference", models.CharField(blank=True, max_length=120)), ("created_at", models.DateTimeField(auto_now_add=True)), ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("variant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_entries", to="catalog.productvariant")), ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_entries", to="catalog.warehouse"))]),
        migrations.CreateModel(name="PriceRule", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("percentage", models.PositiveIntegerField(blank=True, null=True)), ("fixed_price_minor", models.PositiveBigIntegerField(blank=True, null=True)), ("starts_at", models.DateTimeField()), ("ends_at", models.DateTimeField(blank=True, null=True)), ("is_active", models.BooleanField(default=True)), ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="price_rules", to="shops.shop")), ("variant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="price_rules", to="catalog.productvariant"))]),
        migrations.CreateModel(name="Promotion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("code", models.CharField(blank=True, max_length=80)), ("kind", models.CharField(choices=[("percentage", "Percentage"), ("fixed", "Fixed amount"), ("buy_get", "Buy X get Y"), ("free_shipping", "Free shipping")], max_length=30)), ("value", models.PositiveBigIntegerField(default=0)), ("minimum_subtotal_minor", models.PositiveBigIntegerField(default=0)), ("usage_limit", models.PositiveIntegerField(blank=True, null=True)), ("per_customer_limit", models.PositiveIntegerField(blank=True, null=True)), ("starts_at", models.DateTimeField()), ("ends_at", models.DateTimeField(blank=True, null=True)), ("is_automatic", models.BooleanField(default=False)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promotions", to="shops.shop"))], options={"indexes": [models.Index(fields=["shop", "is_active", "starts_at", "ends_at"], name="catalog_pr_shop_id_6f1a7d_idx")]})
    ]
