# Generated by Django 6.0.7 on 2026-08-06 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_shop_id_faa853_idx',
            old_name='catalog_pro_shop_id_1ab9c4_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_name_f603c0_idx',
            old_name='catalog_pro_name_34c45a_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='catalog_pro_sku_187601_idx',
            old_name='catalog_pro_sku_3c2d65_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='catalog_pro_product_6c5ee9_idx',
            old_name='catalog_pro_product_70bd5c_idx',
        ),
        migrations.RenameIndex(
            model_name='promotion',
            new_name='catalog_pro_shop_id_e9aa41_idx',
            old_name='catalog_pr_shop_id_6f1a7d_idx',
        ),
        migrations.AddConstraint(
            model_name='bundlecomponent',
            constraint=models.UniqueConstraint(fields=('bundle', 'component'), name='unique_bundle_component'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='unique_shop_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='unique_shop_collection_slug'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='unique_shop_product_slug'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='unique_product_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'sku'), name='unique_product_variant_sku'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('variant', 'warehouse'), name='unique_variant_warehouse_stock'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('shop', 'code'), name='unique_shop_warehouse_code'),
        ),
    ]
