# Generated by Django 6.0.7 on 2026-08-01 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('countries', models.JSONField(default=list, help_text='List of ISO country codes, e.g. ["US", "CA", "GB"]')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(help_text='Carrier name, e.g. "FedEx", "DHL", "UPS"', max_length=100)),
                ('tracking_number', models.CharField(max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing Package'), ('dispatched', 'Dispatched / In Transit'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='preparing', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('sub_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='orders.vendorsuborder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('rate_type', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('weight_based', 'Weight-Based Tier'), ('price_based', 'Price-Based Tier')], default='flat_rate', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_days', models.CharField(blank=True, help_text='Estimated delivery window, e.g. "3-5 business days"', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['base_rate'],
            },
        ),
    ]
